apiVersion: v1
kind: Service
metadata:
  name: api_gateway
spec:
  selector:
    app: api_gateway
  ports:
    - protocol: TCP
      port: 8005
      targetPort: 8005
  type: LoadBalancer  # Permet d'exposer l'API Gateway en externe
