apiVersion: apps/v1
kind: Deployment
metadata:
  name: price-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: price_service_db
  template:
    metadata:
      labels:
        app: price_service_db
    spec:
      containers:
      - name: price_service_db
        image: assiadoc/postgres:13
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "1234"
        - name: POSTGRES_DB
          value: "carbon_prices"
        volumeMounts:
        - name: price-db-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: price-db-storage
        persistentVolumeClaim:
          claimName: price-db-pvc
