apiVersion: v1
kind: Service
metadata:
  name: transaction_service
spec:
  selector:
    app: transaction_service
  ports:
    - protocol: TCP
      port: 8003
      targetPort: 8003
  type: NodePort
