apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction_db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transaction_db
  template:
    metadata:
      labels:
        app: transaction_db
    spec:
      containers:
      - name: transaction_db
        image: assiadoc/postgres:13
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "1234"
        - name: POSTGRES_DB
          value: "transaction_service_db"
        volumeMounts:
        - name: transaction-db-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: transaction-db-storage
        persistentVolumeClaim:
          claimName: transaction-db-pvc
