apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction_service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: transaction_service
  template:
    metadata:
      labels:
        app: transaction_service
    spec:
      containers:
      - name: transaction_service
        image: assiadoc/backend-transaction_service:v1
        ports:
        - containerPort: 8003
        env:
        - name: DB_HOST
          value: "transaction_db"
        - name: DB_USER
          value: "postgres"
        - name: DB_PASSWORD
          value: "1234"
        - name: DB_NAME
          value: "transaction_service_db"
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka:9092"
