apiVersion: apps/v1
kind: Deployment
metadata:
  name: user_db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user_db
  template:
    metadata:
      labels:
        app: user_db
    spec:
      containers:
      - name: user_db
        image: assiadoc/postgres:13
        env:
        - name: POSTGRES_DB
          value: "user_service_db"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "1234"
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: user-db-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: user-db-storage
        persistentVolumeClaim:
          claimName: user-db-pvc


